meta_product_name: "Remotescanner"
meta_title: "Remotescanner: Find all your dream jobs in one place"
meta_description: "Remotescanner simplify the process of finding remote & work-from-home jobs."
meta_image: "remote-scanner.jpeg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
